#!/usr/bin/env bash
function sync() {
    compile_blog
    aws s3 sync . s3://macchaffee --exclude '*' \
        --include 'index.html' \
        --include 'css/*' \
        --include 'js/*' \
        --include 'static/*' \
        --include 'blog/*' \
        --include 'abgd/*' \
        --delete \
        --cache-control 'max-age=86400'
}

function server() {
    python3 -m http.server 8000
}

function blog() {
    cd blog_jekyll
    jekyll build -d ../blog --watch
}

function compile_blog() {
    cd blog_jekyll
    jekyll build -d ../blog
    cd -
}

function dev() {
    blog & server
}

"$@"
